kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: submodules
    commands:
      - git submodule update --init --recursive

  - name: build
    commands:
      - zola build

  - name: deploy
    commands:
      - POD_NAME=$(microk8s.kubectl get pods -l app.kubernetes.io/instance=blog -o custom-columns=:metadata.name | tr -d '[:space:]')
      - if [ -z "$POD_NAME" ]; then echo "No pod found"; exit 1; fi
      - echo "$POD_NAME"
      - #microk8s.kubectl cp ./public $POD_NAME:/usr/share/nginx/html
      - #microk8s.kubectl exec $POD_NAME -- nginx -s reload

trigger:
  branch:
    - master
  event:
    - push